version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: aathidb
      POSTGRES_PASSWORD: aathipassword
      POSTGRES_USER: aathisuser
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - /var/wiki/data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: aathiuser
      DB_PASS: aathipassword
      DB_NAME: aathidb
    restart: unless-stopped
    ports:
      - "3000:3000"

volumes:
  db-data:
